### ISSUE TITLE
Decrypt prompt is far to the right on widescreen monitors

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/plymouth-theme#22] opened 2021-11-02 17:30 UTC
It started sometime in September and may have been introduced with a Plymouth update.

![IMG_0054](https://user-images.githubusercontent.com/3430283/139915776-2f41e4b7-b05d-4a6d-b8d2-32372b15cef9.jpg)

**Comment by leviport** [comment] 2021-11-02 17:39
Looks like this might be a duplicate of https://github.com/pop-os/plymouth-theme/issues/19

**Comment by 13r0ck** [comment] 2021-11-12 01:44
Should be closed because of #25

**Comment by leviport** [comment] 2021-11-12 16:05
Closing because we think it's fixed. Can reopen if we're mistaken.

**Closed as completed by leviport** 2021-11-12 16:05 UTC

**Comment by crawfxrd** [comment] 2022-01-26 15:48
This will happen on oryp6 and kudu6 if the NVIDIA modules are added to initramfs, which is needed for Plymouth to show on external displays.

**Comment by 13r0ck** [comment] 2022-02-08 20:40
@crawfxrd what are the steps to add the modules? I am trying to reproduce this (and test a fix on the kudu6)

**Comment by crawfxrd** [comment] 2022-02-08 20:49
```
echo "nvidia-drm" | sudo tee /usr/share/initramfs-tools/modules.d/s76-nvidia-drm.conf
sudo update-initramfs -k all
```

**Comment by 13r0ck** [comment] 2022-02-08 20:57
Thanks! This is fixed on the kudu with #28
