### ISSUE TITLE
Decryption screen doesnt show for kernels 6.0.6 and 6.0.12 for Nvidia driver 525

### ISSUE THREAD

**Issue by segmentationsingularity** [pop-os/plymouth-theme#33] opened 2022-12-23 14:22 UTC
Some time ago I opened a new issue regarding the disappeared loginprompt after applying a new kernel suggested by the Pop!_shop and marked it solved after downgrading to the previous kernel.
(https://github.com/pop-os/plymouth-theme/issues/31#issue-1353950982)

However it still doesn't seem to be working for me for new kernels:
6.0.6 and 6.0.12 and Nvidia driver 525 (it did work for kernel 6.0.2)
It shows the BIOS Logo of the mainboard and pressing ESC doesn't do anything, 
however entering the password "blind" does work and brings up the user login prompt.
 
I did another test and disabled the Nvidia graphics card and used the embedded VGA graphics card (server board) 
and that worked, the decryption screen was displayed. 
So I assume its related to the NVidia drivers and to be sure I ran:
sudo update-initramfs -u -k all

However did didn't fix the login screen. Feel free to close this issue however I thought it might help to bring this up in case other users are also affected.

**Comment by leviport** [comment] 2023-01-06 14:54
Duplicate of https://github.com/pop-os/plymouth-theme/issues/31

**Closed as completed by leviport** 2023-01-06 14:54 UTC
